// <auto-generated />
namespace EventManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newOne : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newOne));
        
        string IMigrationMetadata.Id
        {
            get { return "201808240942322_newOne"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
